/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.chromium.ui;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static int color_picker_background_color=0x7f050001;
        public static int color_picker_border_color=0x7f050000;
        public static int dropdown_dark_divider_color=0x7f050003;
        public static int dropdown_divider_color=0x7f050002;
    }
    public static final class dimen {
        public static int color_button_height=0x7f060001;
        /** 
         14.5 = Seekbar thumb width - border width, but it depends on the width
         of the seek bar icon.
    
         */
        public static int color_picker_gradient_margin=0x7f060000;
        /** 
         Fallback values if the corresponding com.android.internal.R dimensions
         cannot be retrieved by name.
         Note: Constants taken directly from Android's core/res/values/config.xml.
    
         */
        public static int config_min_scaling_span=0x7f060004;
        public static int config_min_scaling_touch_major=0x7f060005;
        public static int dropdown_item_divider_height=0x7f060003;
        public static int dropdown_item_height=0x7f060002;
    }
    public static final class drawable {
        public static int color_button_background=0x7f020000;
        public static int color_picker_advanced_select_handle=0x7f020001;
        public static int color_picker_border=0x7f020002;
        public static int dropdown_popup_background=0x7f020003;
        public static int dropdown_popup_background_down=0x7f020004;
        public static int dropdown_popup_background_up=0x7f020005;
        public static int refresh_blue=0x7f020006;
        public static int refresh_gray=0x7f020007;
        public static int verify_checkmark=0x7f020008;
    }
    public static final class id {
        public static int ampm=0x7f08001b;
        public static int color_button_swatch=0x7f08001f;
        public static int color_picker_advanced=0x7f080005;
        public static int color_picker_simple=0x7f080006;
        public static int date_picker=0x7f08000c;
        public static int date_time_suggestion=0x7f08000e;
        public static int date_time_suggestion_label=0x7f080010;
        public static int date_time_suggestion_value=0x7f08000f;
        public static int dropdown_icon=0x7f080014;
        public static int dropdown_label=0x7f080012;
        public static int dropdown_label_wrapper=0x7f080011;
        public static int dropdown_popup_window=0x7f080000;
        public static int dropdown_sublabel=0x7f080013;
        public static int gradient=0x7f080003;
        public static int gradient_border=0x7f080002;
        public static int hour=0x7f080015;
        public static int milli=0x7f08001a;
        public static int minute=0x7f080016;
        public static int more_colors_button=0x7f080008;
        public static int more_colors_button_border=0x7f080007;
        public static int pickers=0x7f08001c;
        public static int position_in_year=0x7f08001d;
        public static int second=0x7f080018;
        public static int second_colon=0x7f080017;
        public static int second_dot=0x7f080019;
        public static int seek_bar=0x7f080004;
        public static int selected_color_view=0x7f08000b;
        public static int selected_color_view_border=0x7f08000a;
        public static int text=0x7f080001;
        public static int time_picker=0x7f08000d;
        public static int title=0x7f080009;
        public static int year=0x7f08001e;
    }
    public static final class layout {
        public static int color_picker_advanced_component=0x7f030000;
        public static int color_picker_dialog_content=0x7f030001;
        public static int color_picker_dialog_title=0x7f030002;
        public static int date_time_picker_dialog=0x7f030003;
        public static int date_time_suggestion=0x7f030004;
        public static int dropdown_item=0x7f030005;
        public static int multi_field_time_picker_dialog=0x7f030006;
        public static int two_field_date_picker=0x7f030007;
    }
    public static final class string {
        public static int accessibility_date_picker_month=0x7f040012;
        public static int accessibility_date_picker_week=0x7f040016;
        public static int accessibility_date_picker_year=0x7f040013;
        public static int accessibility_datetime_picker_date=0x7f040024;
        public static int accessibility_datetime_picker_time=0x7f040025;
        public static int accessibility_time_picker_ampm=0x7f04001f;
        public static int accessibility_time_picker_hour=0x7f04001b;
        public static int accessibility_time_picker_milli=0x7f04001e;
        public static int accessibility_time_picker_minute=0x7f04001c;
        public static int accessibility_time_picker_second=0x7f04001d;
        public static int color_picker_button_black=0x7f04000f;
        public static int color_picker_button_blue=0x7f04000b;
        public static int color_picker_button_cancel=0x7f040007;
        public static int color_picker_button_cyan=0x7f04000a;
        public static int color_picker_button_green=0x7f04000c;
        public static int color_picker_button_magenta=0x7f04000d;
        public static int color_picker_button_more=0x7f040002;
        public static int color_picker_button_red=0x7f040009;
        public static int color_picker_button_set=0x7f040006;
        public static int color_picker_button_white=0x7f040010;
        public static int color_picker_button_yellow=0x7f04000e;
        public static int color_picker_dialog_title=0x7f040008;
        public static int color_picker_hue=0x7f040003;
        public static int color_picker_saturation=0x7f040004;
        public static int color_picker_value=0x7f040005;
        public static int copy_to_clipboard_failure_message=0x7f040011;
        public static int date_picker_dialog_clear=0x7f040028;
        public static int date_picker_dialog_other_button_label=0x7f040026;
        public static int date_picker_dialog_set=0x7f040014;
        public static int date_picker_dialog_title=0x7f040027;
        public static int date_time_picker_dialog_title=0x7f040023;
        public static int low_memory_error=0x7f040000;
        public static int month_picker_dialog_title=0x7f040015;
        public static int opening_file_error=0x7f040001;
        public static int time_picker_dialog_am=0x7f040018;
        public static int time_picker_dialog_hour_minute_separator=0x7f040020;
        public static int time_picker_dialog_minute_second_separator=0x7f040021;
        public static int time_picker_dialog_pm=0x7f040019;
        public static int time_picker_dialog_second_subsecond_separator=0x7f040022;
        public static int time_picker_dialog_title=0x7f04001a;
        public static int week_picker_dialog_title=0x7f040017;
    }
    public static final class style {
        public static int DropdownPopupWindow=0x7f070000;
    }
}
