local_dir := $(ROOT_DIR)/src2
local_src := test.cpp
local_objects := $(local_src:%.cpp=$(local_dir)/objs/%.o)
local_targets := $(local_src:%.cpp=$(local_dir)/bin/%)

all_objects += $(local_objects)

all_targets += $(local_targets)
