# Source: http://www.makelinux.net/make3/make3-CHP-6-SECT-2

root_dir := this
this_dir := $(root_dir)

all:

target_dir := L1.1
include $(target_dir)/Makefile

target_dir := L1.2
include $(target_dir)/Makefile

# define any target after including all files
include Makerules.mk
